title: Deep Saliency
logo: /assets/img/logo.png
description: EFRI BRAID: Using Proto-Object Based Saliency Inspired by Cortical Local Circuits to Limit the Hypothesis Space for Deep Learning Models.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
